[tool.poetry]
name = "test-gh-actions"
version = "0.1.0"
description = ""
authors = ["Lukasz Obara <lukasz48@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
